title = "Configuration to finetune HistoSam with the uni-2h encoder"

[training]
points = true
box = true
negative_points = true
mask_prompt = true

n_points = 5
n_neg_points = 5
points_near_center = 4
random_box_shift = 20

mask_prompt_type = 'loose_dilation' # 'truth', 'morphology', 'scribble', 'loose_dilation'
negative_points_inside_box = true
box_around_prompt_mask = false

use_img_embeddings = true
is_combined_embedding = true

prompt_on_get = false

batch_size = 32
lr = 1e-5
epochs = 30
train_from_last_checkpoint = false
last_checkpoint_path = ''
last_model_path = ''
model_save_dir = '/content/drive/MyDrive/TFE/results/finetuning/histosam/sam_with_uni2h/'
load_on_cpu = false

[validation]
frequency = 1

[sam]
model_type = 'vit_b'
not_use_sam_encoder = false
input_size = 1024

[encoder]
type = 'uni-2h'
deconv = true

[misc]
device = 'cuda'
wandb = true
project_name = 'Finetuning_SAM_WITH_UNI2H'