title = "Configuration to test SAM"

[testing]
points = true
box = true
negative_points = true
mask_prompt = true
n_points = 5
n_neg_points = 5
negative_points_inside_box = true
points_near_center = 4
random_box_shift = 20
mask_prompt_type = 'loose_dilation' # 'truth', 'morphology', 'scribble', 'loose_dilation'
box_around_prompt_mask = false
use_img_embeddings = true
batch_size = 16

[sam]
model_type = 'vit_b'
input_size = 1024
last_model_path = ''
input_mask_eval = false

[misc]
device = 'cuda'