title = "Configuration to test SAM2 with positive point prompt"

[testing]
points = true
box = false
negative_points = false
mask_prompt = false
n_points = 5
n_neg_points = 0
negative_points_inside_box = false
points_near_center = 4
random_box_shift = 20
mask_prompt_type = 'loose_dilation' # 'truth', 'morphology', 'scribble', 'loose_dilation'
box_around_prompt_mask = false
use_img_embeddings = false
batch_size = 16

[sam2]
model_name = 'testing'
model_type = 'sam2.1_hiera_b+.yaml'
train_prompt_encoder = false
train_mask_decoder = false
input_size = 1024
last_model_path = ''
input_mask_eval = false

[misc]
device = 'cuda'