title = "Scraper for LBTD-NEO04"

# LBTD-NEO04
[cytomine]
dataset_path = "datasets/LBTD-NEO04/"
project_id = '51066666'
annotation_users_id = ['701', '23245043', '34451686', '8106092']
random_shift = 0
random_state = 42
zoom_out_factor = 2.0

[sam]
input_size = 1024