title = "Evaluation for Hiera Tiny encoder"

[prompting_evaluation]
points = false
negative_points = false
box = true
mask_prompt = false
n_points = 0
n_neg_points = 0
use_img_embeddings = false
negative_points_inside_box = false
points_near_center = 4 # The higher the value, the closer to the center of mask the points have a chance to be. -1 means no restriction
random_box_shift = 20 # Random shift in the box position in pixels (simulates the annotation error of an expert)
mask_prompt_type = 'scribble' # 'truth', 'morphology', 'scribble', 'loose_dilation'
box_around_prompt_mask = false
batch_size = 1
input_mask_eval = false

[sam]
model_type = 'vit_h'    # 'vit_b', 'vit_l', 'vit_h'
input_size = 1024


[sam2]
model_type = 'sam2.1_hiera_t.yaml'

[misc]
device = 'cuda' # 'cuda' or 'cpu'